# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20_170_118_130_314) do
  # These are extensions that must be enabled in order to support this database
  enable_extension 'plpgsql'

  create_table 'entreprises', force: :cascade do |t|
    t.string   'siren'
    t.string   'siret'
    t.string   'nic'
    t.string   'l1_normalisee'
    t.string   'l2_normalisee'
    t.string   'l3_normalisee'
    t.string   'l4_normalisee'
    t.string   'l5_normalisee'
    t.string   'l6_normalisee'
    t.string   'l7_normalisee'
    t.string   'l1_declaree'
    t.string   'l2_declaree'
    t.string   'l3_declaree'
    t.string   'l4_declaree'
    t.string   'l5_declaree'
    t.string   'l6_declaree'
    t.string   'l7_declaree'
    t.string   'numero_voie'
    t.string   'indice_repetition'
    t.string   'type_voie'
    t.string   'libelle_voie'
    t.string   'code_postal'
    t.string   'cedex'
    t.string   'region'
    t.string   'libelle'
    t.string   'departement'
    t.string   'arrondissement'
    t.string   'canton'
    t.string   'commune'
    t.string   'libelle_commune'
    t.string   'departement_unite_urbaine'
    t.string   'taille_unite_urbaine'
    t.string   'numero_unite_urbaine'
    t.string   'etablissement_public_cooperation_intercommunale'
    t.string   'tranche_commune_detaillee'
    t.string   'zone_emploi'
    t.string   'is_siege'
    t.string   'enseigne'
    t.string   'indicateur_champ_publipostage'
    t.string   'statut_diffusion'
    t.string   'date_introduction_base_diffusion'
    t.string   'nature_entrepreneur_individuel'
    t.string   'libelle_nature_entrepreneur_individuel'
    t.string   'activite_principale'
    t.string   'libelle_activite_principale'
    t.string   'date_validite_activite_principale'
    t.string   'tranche_effectif_salarie'
    t.string   'libelle_tranche_effectif_salarie'
    t.string   'tranche_effectif_salarie_centaine_pret'
    t.string   'date_validite_effectif_salarie'
    t.string   'origine_creation'
    t.string   'date_creation'
    t.string   'date_debut_activite'
    t.string   'nature_activite'
    t.string   'lieu_activite'
    t.string   'type_magasin'
    t.string   'is_saisonnier'
    t.string   'modalite_activite_principale'
    t.string   'caractere_productif'
    t.string   'participation_particuliere_production'
    t.string   'caractere_auxiliaire'
    t.string   'nom_raison_sociale'
    t.string   'sigle'
    t.string   'nom'
    t.string   'prenom'
    t.string   'civilite'
    t.string   'numero_rna'
    t.string   'nic_siege'
    t.string   'region_siege'
    t.string   'departement_commune_siege'
    t.string   'email'
    t.string   'nature_juridique_entreprise'
    t.string   'libelle_nature_juridique_entreprise'
    t.string   'activite_principale_entreprise'
    t.string   'libelle_activite_principale_entreprise'
    t.string   'date_validite_activite_principale_entreprise'
    t.string   'activite_principale_registre_metier'
    t.string   'is_ess'
    t.string   'date_ess'
    t.string   'tranche_effectif_salarie_entreprise'
    t.string   'libelle_tranche_effectif_salarie_entreprise'
    t.string   'tranche_effectif_salarie_entreprise_centaine_pret'
    t.string   'date_validite_effectif_salarie_entreprise'
    t.string   'categorie_entreprise'
    t.string   'date_creation_entreprise'
    t.string   'date_introduction_base_diffusion_entreprise'
    t.string   'indice_monoactivite_entreprise'
    t.string   'modalite_activite_principale_entreprise'
    t.string   'caractere_productif_entreprise'
    t.string   'date_validite_rubrique_niveau_entreprise_esa'
    t.string   'tranche_chiffre_affaire_entreprise_esa'
    t.string   'activite_principale_entreprise_esa'
    t.string   'premiere_activite_secondaire_entreprise_esa'
    t.string   'deuxieme_activite_secondaire_entreprise_esa'
    t.string   'troisieme_activite_secondaire_entreprise_esa'
    t.string   'quatrieme_activite_secondaire_entreprise_esa'
    t.string   'nature_mise_a_jour'
    t.string   'indicateur_mise_a_jour_1'
    t.string   'indicateur_mise_a_jour_2'
    t.string   'indicateur_mise_a_jour_3'
    t.string   'date_mise_a_jour'
    t.string   'type_evenement'
    t.string   'date_evenement'
    t.string   'type_creation'
    t.string   'date_reactivation_etablissement'
    t.string   'date_reactivation_entreprise'
    t.string   'indicateur_mise_a_jour_enseigne_entreprise'
    t.string   'indicateur_mise_a_jour_activite_principale_etablissement'
    t.string   'indicateur_mise_a_jour_adresse_etablissement'
    t.string   'indicateur_mise_a_jour_caractere_productif_etablissement'
    t.string   'indicateur_mise_a_jour_caractere_auxiliaire_etablissement'
    t.string   'indicateur_mise_a_jour_nom_raison_sociale'
    t.string   'indicateur_mise_a_jour_sigle'
    t.string   'indicateur_mise_a_jour_nature_juridique'
    t.string   'indicateur_mise_a_jour_activite_principale_entreprise'
    t.string   'indicateur_mise_a_jour_caractere_productif_entreprise'
    t.string   'indicateur_mise_a_jour_nic_siege'
    t.string   'siret_predecesseur_successeur'
    t.string   'telephone'
    t.datetime 'created_at',                                                null: false
    t.datetime 'updated_at',                                                null: false
    t.index ['nom'], name: 'index_entreprises_on_nom', using: :btree
    t.index ['nom_raison_sociale'], name: 'index_entreprises_on_nom_raison_sociale', using: :btree
    t.index ['siren'], name: 'index_entreprises_on_siren', using: :btree
  end
end
